// export const ADD_USER = "ADD_USER";
export const ADD_TRACKER = "ADD_TRACKER";
export const UPDATE_TRACKER = "UPDATE_TRACKER";
export const ADD_MULTIPLE_TO_TRACKER = "ADD_MULTIPLE_TO_TRACKER";
export const REMOVE_FROM_TRACKER = "REMOVE_FROM_TRACKER";
export const UPDATE_KEYS = "UPDATE_KEYS";
export const UPDATE_CURRENT_KEY = "UPDATE_CURRENT_KEY";
